---
title: "In-Class Slides & Reading for CS631 Labs"
output: html_document
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warnings = FALSE, errors = FALSE, messages = FALSE, tidy = FALSE, echo = FALSE)
```

The following are all *free* books, available to read online:

- Modern Dive: http://moderndive.com
- R for Data Science: http://r4ds.had.co.nz
- Fundamentals of Data Visualization: http://serialmentor.com/dataviz/
- Data Visualization: A Practical Introduction: http://socviz.co

## Slide Decks & Reading {.tabset}

### 01: Working in R

```{r}
knitr::include_url("slides/01-slides.html")
```

- R for Data Science, Workflow: Basics Chapter: http://r4ds.had.co.nz/workflow-basics.html

- Modern Dive, Getting Started Chapter: http://moderndive.com/2-getting-started.html

- R & RStudio Basics: https://bookdown.org/chesterismay/rbasics/3-rstudiobasics.html

- RStudio IDE Cheatsheet: https://github.com/rstudio/cheatsheets/blob/master/rstudio-ide.pdf

